const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');
const https = require('https');
const http = require('http');
const fs = require('fs');
const path = require('path');

const RECEIPTS_DIR = path.join(__dirname, '../../uploads/receipts');
// Create directory on first load if it doesn't exist
if (!fs.existsSync(RECEIPTS_DIR)) fs.mkdirSync(RECEIPTS_DIR, { recursive: true });

function fetchImageBuffer(url) {
  return new Promise((resolve) => {
    const client = url.startsWith('https') ? https : http;
    client.get(url, (res) => {
      if (res.statusCode !== 200) return resolve(null);
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
      res.on('error', () => resolve(null));
    }).on('error', () => resolve(null));
  });
}

async function generateReceiptPdf(data) {
  const {
    receipt_number,
    issued_by,
    issued_to,
    date,
    description,
    amount,
    currency = 'XCD',
    status = 'PAID',
    logo_url,
    verify_url,
  } = data;

  const qrBuf = verify_url ? await QRCode.toBuffer(verify_url, { type: 'png', width: 96, margin: 1 }) : null;
  const filePath = path.join(RECEIPTS_DIR, `receipt-${receipt_number}.pdf`);

  await new Promise(async (resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const writeStream = fs.createWriteStream(filePath);
    doc.pipe(writeStream);

    const pageWidth = doc.page.width - 100;
    const topY = 50;

    let headerBottomY = topY;

    if (logo_url) {
      const imgBuf = await fetchImageBuffer(logo_url).catch(() => null);
      if (imgBuf) {
        try {
          doc.image(imgBuf, 50, topY, { height: 70, fit: [140, 70] });
        } catch {
          // skip logo if format unsupported (e.g. WebP/AVIF)
        }
      }
    }

    doc
      .font('Helvetica-Bold')
      .fontSize(20)
      .fillColor('#111111')
      .text(issued_by || 'Business', 50, topY, { align: 'right', width: pageWidth });

    headerBottomY = Math.max(topY + 70, doc.y + 10);
    doc.moveTo(50, headerBottomY + 10).lineTo(545, headerBottomY + 10).strokeColor('#cccccc').stroke();

    doc
      .font('Helvetica-Bold')
      .fontSize(26)
      .fillColor('#111111')
      .text('OFFICIAL RECEIPT', 50, headerBottomY + 30, { align: 'center', width: pageWidth });

    doc
      .font('Helvetica')
      .fontSize(11)
      .fillColor('#555555')
      .text(`Receipt No: ${receipt_number}`, { align: 'center', width: pageWidth })
      .text(`Date: ${date || new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`, { align: 'center', width: pageWidth });

    doc.moveDown(1.2);

    const fromToY = doc.y;
    doc
      .font('Helvetica-Bold').fontSize(10).fillColor('#888888')
      .text('FROM', 50, fromToY)
      .font('Helvetica').fontSize(12).fillColor('#111111')
      .text(issued_by, 50, fromToY + 14);

    doc
      .font('Helvetica-Bold').fontSize(10).fillColor('#888888')
      .text('TO', 300, fromToY)
      .font('Helvetica').fontSize(12).fillColor('#111111')
      .text(issued_to || 'Customer', 300, fromToY + 14);

    doc.moveDown(3);

    const divY = doc.y;
    doc.moveTo(50, divY).lineTo(545, divY).strokeColor('#cccccc').stroke();
    doc.moveDown(1);

    const descY = doc.y;
    doc.roundedRect(50, descY, pageWidth, 60, 6).fillColor('#f7f7f7').fill();
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#888888').text('DESCRIPTION', 65, descY + 10);
    doc.font('Helvetica').fontSize(12).fillColor('#111111').text(description || '', 65, descY + 26, { width: pageWidth - 30 });

    doc.moveDown(4.5);

    doc
      .font('Helvetica-Bold')
      .fontSize(32)
      .fillColor('#1a1a1a')
      .text(`$${Number(amount).toFixed(2)} ${currency}`, { align: 'center', width: pageWidth });

    doc.moveDown(0.6);

    const badgeText = (status || 'PAID').toUpperCase();
    const badgeX = (doc.page.width - 80) / 2;
    const badgeY = doc.y;
    doc.roundedRect(badgeX, badgeY, 80, 24, 12).fillColor('#22c55e').fill();
    doc.font('Helvetica-Bold').fontSize(12).fillColor('#ffffff').text(badgeText, badgeX, badgeY + 6, { width: 80, align: 'center' });

    doc.moveDown(4);

    doc
      .moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#eeeeee').stroke()
      .moveDown(0.8)
      .font('Helvetica').fontSize(9).fillColor('#aaaaaa')
      .text('Generated by Bridge Agent — BridgePro Caribbean Marketplace', { align: 'center', width: pageWidth });

    // QR verification block
    if (qrBuf) {
      const QR_SIZE = 52;
      const qrX = (doc.page.width - QR_SIZE) / 2;
      doc.moveDown(1.2);
      doc.image(qrBuf, qrX, doc.y, { width: QR_SIZE, height: QR_SIZE });
      doc.save()
        .fontSize(7).font('Helvetica').fillColor('#aaaaaa')
        .text('Scan to verify authenticity at BridgePro', 50, doc.y + QR_SIZE + 4, { align: 'center', width: pageWidth })
        .restore();
    }

    doc.end();
    writeStream.on('finish', resolve);
    writeStream.on('error', reject);
  });

  return filePath;
}

module.exports = generateReceiptPdf;
