const express = require('express');
const { v4: uuidv4 } = require('uuid');
const db = require('../db');
const { requireAuth } = require('../middleware/auth');
const { upload } = require('../middleware/upload');
const { lookupSignature } = require('../utils/docSignature');

const router = express.Router();

const DOC_TYPE_LABELS = {
  receipt:        'Official Receipt',
  invoice:        'Invoice',
  credit_memo:    'MSME Credit Profile',
  payroll_report: 'Statutory Payroll Report',
  payslip:        'Employee Payslip',
};

const COUNTRY_NAMES = {
  SVG: 'Saint Vincent and the Grenadines', GRD: 'Grenada', BRB: 'Barbados',
  SLU: 'Saint Lucia', JAM: 'Jamaica', TTO: 'Trinidad and Tobago',
  ATG: 'Antigua and Barbuda', SKN: 'Saint Kitts and Nevis', DMA: 'Dominica',
};

function verifyHtml({ valid, doc_type, metadata = {}, country_code, created_at, token }) {
  const label = DOC_TYPE_LABELS[doc_type] || doc_type || 'Document';
  const country = COUNTRY_NAMES[country_code] || country_code || '';
  const issued = created_at
    ? new Date(created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    : '';

  const rows = [];
  if (metadata.issued_by)   rows.push(['Issued By',    metadata.issued_by]);
  if (metadata.issued_to)   rows.push(['Issued To',    metadata.issued_to]);
  if (metadata.amount != null && metadata.currency)
    rows.push(['Amount', `${metadata.currency} $${Number(metadata.amount).toFixed(2)}`]);
  if (metadata.description) rows.push(['Description',  metadata.description]);
  if (metadata.period)      rows.push(['Period',        metadata.period]);
  if (country)              rows.push(['Jurisdiction',  country]);
  if (issued)               rows.push(['Document Date', issued]);
  if (token)                rows.push(['Token',         token]);

  const tableRows = rows.map(([k, v]) =>
    `<tr><td class="k">${k}</td><td class="v">${v}</td></tr>`
  ).join('');

  const badge = valid
    ? `<div class="badge ok"><span class="mark">✓</span> GENUINE</div>`
    : `<div class="badge fail"><span class="mark">✗</span> NOT FOUND</div>`;

  const body = valid
    ? `<p class="doc-label">${label}</p>${tableRows ? `<table>${tableRows}</table>` : ''}
       <p class="note">This document was generated by BridgePro and its authenticity has been verified against the platform database.</p>`
    : `<p class="msg">This token does not match any document issued by BridgePro. The document may be fraudulent or the QR code may be damaged.</p>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>BridgePro — Document Verification</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f0f4f8;min-height:100vh;display:flex;flex-direction:column;align-items:center;padding:32px 16px}
  .card{background:#fff;border-radius:16px;box-shadow:0 4px 24px rgba(0,0,0,0.10);max-width:520px;width:100%;overflow:hidden}
  .header{background:#0A2240;padding:24px 28px 20px;display:flex;align-items:center;gap:14px}
  .header .logo{font-size:1.3rem;font-weight:800;color:#fff;letter-spacing:-0.5px}
  .header .logo span{color:#009E60}
  .header .sub{font-size:0.78rem;color:rgba(255,255,255,0.55);margin-top:2px}
  .body{padding:28px}
  .badge{display:flex;align-items:center;gap:10px;font-size:1.1rem;font-weight:800;letter-spacing:0.04em;padding:14px 20px;border-radius:10px;margin-bottom:20px}
  .badge.ok{background:#d1fae5;color:#065f46}.badge.ok .mark{background:#009E60;color:#fff;border-radius:50%;width:28px;height:28px;display:flex;align-items:center;justify-content:center;font-size:1rem;flex-shrink:0}
  .badge.fail{background:#fee2e2;color:#991b1b}.badge.fail .mark{background:#dc2626;color:#fff;border-radius:50%;width:28px;height:28px;display:flex;align-items:center;justify-content:center;font-size:1rem;flex-shrink:0}
  .doc-label{font-size:0.7rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#6b7280;margin-bottom:12px}
  table{width:100%;border-collapse:collapse;margin-bottom:16px}
  td{padding:8px 0;font-size:0.88rem;border-bottom:1px solid #f3f4f6;vertical-align:top}
  td.k{color:#6b7280;width:38%;padding-right:12px}
  td.v{color:#111827;font-weight:500;word-break:break-all}
  .note{font-size:0.78rem;color:#6b7280;line-height:1.6;padding:12px 14px;background:#f9fafb;border-radius:8px;border-left:3px solid #009E60}
  .msg{font-size:0.9rem;color:#7f1d1d;line-height:1.6}
  .footer{margin-top:20px;font-size:0.72rem;color:#9ca3af;text-align:center}
  .stripe{height:4px;background:#009E60}
</style>
</head>
<body>
<div class="card">
  <div class="header">
    <div>
      <div class="logo">Bridge<span>Pro</span></div>
      <div class="sub">Document Verification Portal</div>
    </div>
  </div>
  <div class="stripe"></div>
  <div class="body">
    ${badge}
    ${body}
  </div>
</div>
<div class="footer">BridgePro Marketplace · Caribbean Service Economy Infrastructure<br>For fraud reports contact support@bridgepro.a3tech.uk</div>
</body>
</html>`;
}

// GET /verify/doc/:token — public, no auth required
router.get('/doc/:token', async (req, res, next) => {
  try {
    const sig = await lookupSignature(req.params.token);
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.send(verifyHtml(sig
      ? { valid: true, ...sig }
      : { valid: false, token: req.params.token }
    ));
  } catch (err) {
    next(err);
  }
});

const idFields = upload('id_verifications').fields([
  { name: 'file', maxCount: 1 },
  { name: 'rep_file', maxCount: 1 },
]);

// POST /verify/id — upload government ID (+ representative ID for small_business)
router.post('/id', requireAuth, idFields, async (req, res, next) => {
  try {
    const idFile = req.files?.file?.[0];
    if (!idFile) return res.status(400).json({ error: 'No file uploaded' });

    const userRow = await db.query('SELECT account_type FROM users WHERE id = $1', [req.user.id]);
    const accountType = userRow.rows[0]?.account_type;

    if (accountType === 'small_business') {
      const repFile = req.files?.rep_file?.[0];
      const repName = req.body?.rep_name?.trim();
      if (!repName) return res.status(400).json({ error: 'rep_name is required for small business accounts' });
      if (!repFile) return res.status(400).json({ error: 'Representative ID document is required for small business accounts' });
    }

    const existing = await db.query(
      'SELECT id, status FROM id_verifications WHERE user_id = $1 AND country_code = $2 ORDER BY created_at DESC LIMIT 1',
      [req.user.id, req.countryCode]
    );

    if (existing.rows.length && existing.rows[0].status === 'pending') {
      return res.status(409).json({ error: 'You already have a pending ID verification' });
    }

    const repFile = req.files?.rep_file?.[0];
    const repName = req.body?.rep_name?.trim() || null;
    const repDocUrl = repFile ? `/uploads/id_verifications/${repFile.filename}` : null;

    const result = await db.query(
      `INSERT INTO id_verifications (id, user_id, country_code, id_doc_url, rep_name, rep_id_doc_url)
       VALUES ($1, $2, $3, $4, $5, $6) RETURNING *`,
      [uuidv4(), req.user.id, req.countryCode, `/uploads/id_verifications/${idFile.filename}`, repName, repDocUrl]
    );

    res.status(201).json({ verification: result.rows[0] });
  } catch (err) {
    next(err);
  }
});

// GET /verify/status
router.get('/status', requireAuth, async (req, res, next) => {
  try {
    const result = await db.query(
      `SELECT id, status, rejection_reason, rep_name, rep_id_doc_url, created_at, reviewed_at
       FROM id_verifications WHERE user_id = $1 AND country_code = $2
       ORDER BY created_at DESC LIMIT 1`,
      [req.user.id, req.countryCode]
    );

    const user = await db.query(
      'SELECT is_verified, verified_at, account_type FROM users WHERE id = $1',
      [req.user.id]
    );

    res.json({
      is_verified: user.rows[0].is_verified,
      verified_at: user.rows[0].verified_at,
      account_type: user.rows[0].account_type,
      latest_submission: result.rows[0] || null,
    });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
module.exports.verifyHtml = verifyHtml;
module.exports.lookupSignature = lookupSignature;
